/**
 * Generates the ImageService.ts file with static require() entries
 * for every processed image in assets/images/.
 *
 * Usage: npx ts-node scripts/generateImageMap.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const IMAGES_DIR = path.resolve(__dirname, '../assets/images');
const OUTPUT_FILE = path.resolve(__dirname, '../src/services/ImageService.ts');

function walkDir(dir: string, baseDir: string): string[] {
  const results: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(fullPath, baseDir));
    } else if (entry.name.endsWith('.webp')) {
      const relative = path.relative(baseDir, fullPath);
      results.push(relative);
    }
  }

  return results.sort();
}

function main(): void {
  if (!fs.existsSync(IMAGES_DIR)) {
    console.error(`Images directory not found: ${IMAGES_DIR}`);
    process.exit(1);
  }

  const imageFiles = walkDir(IMAGES_DIR, IMAGES_DIR);
  console.log(`Found ${imageFiles.length} WebP images`);

  const entries = imageFiles.map((filePath) => {
    // Key: category/filename_without_extension
    const key = filePath.replace(/\.webp$/, '');
    return `  '${key}': require('../../assets/images/${filePath}'),`;
  });

  const output = `import { ImageSource } from 'expo-image';

// AUTO-GENERATED by scripts/generateImageMap.ts
// Do not edit manually. Re-run the script after adding/removing images.

const imageMap: Record<string, ImageSource> = {
${entries.join('\n')}
};

export function getImage(imageRef: string): ImageSource | null {
  return imageMap[imageRef] ?? null;
}

export function hasImage(imageRef: string): boolean {
  return imageRef in imageMap;
}

export function getAllImageKeys(): string[] {
  return Object.keys(imageMap);
}
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE} with ${imageFiles.length} entries`);
}

main();
